---
- name: wait for restart
  shell: sleep 15

- name: enable the cluster
  uri: status_code=201 HEADER_Content-Type="application/json" method=POST force_basic_auth=yes body_format=json url=http://admin:{{PASSWORD}}@127.0.0.1:5984/_cluster_setup body='{"action":"enable_cluster","bind_address":"0.0.0.0","username":"admin","password":"{{PASSWORD}}","node_count":"{{ N_NODES }}"}'

- name: add nodes to the cluster
  uri: status_code=201,409 HEADER_Content-Type="application/json" method=POST force_basic_auth=yes body_format=json url=http://admin:{{PASSWORD}}@127.0.0.1:5984/_cluster_setup body='{"action":"add_node","username":"admin","password":"{{ PASSWORD }}","host":"{{ item }}","port":5984}'
  with_items: "{{groups['nodes']}}"
  when: inventory_hostname == "{{ groups.nodes[0] }}" and inventory_hostname != item

- name: finish the cluster
  uri: status_code=201 HEADER_Content-Type="application/json" user=admin password={{ PASSWORD }} method=POST force_basic_auth=yes url=http://127.0.0.1:5984/_cluster_setup body_format=json body='{"action":"finish_cluster"}'
  when: inventory_hostname == "{{ groups.nodes[0] }}"